//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAEncrypting_LR1_Lukoyanov {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSAEncrypting_LR1_Lukoyanov.Strings-ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Choose the option:
        ///1. Encrypt and decrypt entered text
        ///2. Encrypt adn decrypt text file
        ///Type &apos;q&apos; to exit.
        /// </summary>
        internal static string AvailableOptions {
            get {
                return ResourceManager.GetString("AvailableOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose two prime numbers to use RSA algorithm: .
        /// </summary>
        internal static string ChoosePrimes {
            get {
                return ResourceManager.GetString("ChoosePrimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted text:
        ///{0}.
        /// </summary>
        internal static string DecryptedText {
            get {
                return ResourceManager.GetString("DecryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting....
        /// </summary>
        internal static string DecryptingProcess {
            get {
                return ResourceManager.GetString("DecryptingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted file saved at {0}
        ///.
        /// </summary>
        internal static string DecryptionFilePath {
            get {
                return ResourceManager.GetString("DecryptionFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Decryption time: {0}
        ///.
        /// </summary>
        internal static string DecryptionTime {
            get {
                return ResourceManager.GetString("DecryptionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is empty.
        /// </summary>
        internal static string EmptyInput {
            get {
                return ResourceManager.GetString("EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Encrypted bytes:
        ///{0}
        ///.
        /// </summary>
        internal static string EncryptedBytes {
            get {
                return ResourceManager.GetString("EncryptedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting....
        /// </summary>
        internal static string EncryptingProcess {
            get {
                return ResourceManager.GetString("EncryptingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Encrypted file saved at {0}
        ///.
        /// </summary>
        internal static string EncryptionFilePath {
            get {
                return ResourceManager.GetString("EncryptionFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Encryption time: {0}.
        /// </summary>
        internal static string EncryptionTime {
            get {
                return ResourceManager.GetString("EncryptionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the option number: .
        /// </summary>
        internal static string EnterOptionNumber {
            get {
                return ResourceManager.GetString("EnterOptionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file path: .
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First number isn&apos;t prime! Try again.
        /// </summary>
        internal static string FirstNumberIsntPrime {
            get {
                return ResourceManager.GetString("FirstNumberIsntPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is incorrect. Try again or enter &apos;q&apos; to exit.
        /// </summary>
        internal static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect option number. Try again.
        /// </summary>
        internal static string IncorrectOption {
            get {
                return ResourceManager.GetString("IncorrectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is invalid or file doesn&apos;t exist.
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains no content to encrypt.
        /// </summary>
        internal static string NoContentToEncrypt {
            get {
                return ResourceManager.GetString("NoContentToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key: {0}.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Util can encrypt and decrypt text only in ASCII encoding (UTF-8/UTF-16 support coming soon).
        /// </summary>
        internal static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Text Encrypting/Decrypting Util (demonstration).
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Public key: {0}.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second number isn&apos;t prime! Try again.
        /// </summary>
        internal static string SecondNumberIsntPrime {
            get {
                return ResourceManager.GetString("SecondNumberIsntPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to encrypt/decrypt: .
        /// </summary>
        internal static string TextToEncryptDecrypt {
            get {
                return ResourceManager.GetString("TextToEncryptDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Total time passed: {0}.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
    }
}
